#!/bin/bash

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)

if [ -z ${REPO_NAME_FULL} ]; then
	export REPO_NAME_FULL=NERVA
fi

if [ -z ${REPO_NAME} ]; then
	export REPO_NAME=nerva
fi

if [ -z ${BUILD_TYPE} ]; then
	export BUILD_TYPE=release
fi

if [ -z ${STATIC} ]; then
	export STATIC=OFF
fi

if [ -z ${THREAD_COUNT} ]; then
	export THREAD_COUNT=30
fi

if [ -z ${BUILD_GUI_DEPS} ]; then
	export BUILD_GUI_DEPS=OFF
fi

if [ -z ${BUILD_EXTRAS} ]; then
	export BUILD_EXTRAS=OFF
fi

function detectos()
{
	if [ "$(uname)" == "Linux" ]; then
		if [[ -z "${NERVA_BUILD_DISTRO}" ]]; then
			local os_distro="unknown"

			if [ -f /etc/os-release ]; then
				source /etc/os-release
				os_distro=$ID
			elif [ -f /etc/lsb-release ]; then
				source /etc/lsb-release
				os_distro=$DISTRIB_ID
			fi
		fi
		export NERVA_BUILD_OS="linux"
		export NERVA_BUILD_DISTRO=${os_distro}
	elif [ "$(uname)" == "Darwin" ]; then
		export NERVA_BUILD_OS="osx"
	elif [ "$(expr substr $(uname -s) 1 7)" == "MSYS_NT" ] || [ "$(expr substr $(uname -s) 1 7)" == "MINGW64" ]; then
		export NERVA_BUILD_OS="windows"
	else
		echo "Unsupported OS"
		exit 0
	fi

	echo OS detected ${NERVA_BUILD_OS} ${NERVA_BUILD_DISTRO}
}

function detectversion()
{
    ver=$(awk '/#define DEF_MONERO_VERSION /{ print $3 }' < ${NERVA_DIR}/src/version.cpp.in)
	name=$(awk '/#define DEF_MONERO_RELEASE_NAME /{ print $3 }' < ${NERVA_DIR}/src/version.cpp.in)
    export NERVA_VERSION=$(echo ${ver} | tr -d '"')
	export NERVA_CODENAME=$(echo ${name} | tr -d '"')
    echo Version detected as ${REPO_NAME_FULL} ${NERVA_VERSION}: ${NERVA_CODENAME}
}

function set_aes()
{
    no_aes=OFF

	if [ "$1" == "aes" ]; then
		no_aes=OFF
	elif [ "$1" == "noaes" ]; then
		no_aes=ON
	else
		echo "Unsupported configuration" $1
		exit 1
	fi
    
    # We can force to use/not use AES by setting the ${NO_AES} var
    # if not set, it will default to whatever the system decided
    if [ -z ${NO_AES} ]; then
        export NO_AES=${no_aes}
    fi
}

function print_env()
{
	stat="static"
	if [ -z ${STATIC} ] || [ ${STATIC} == "OFF" ]; then
		stat="dynamic"
	fi

	echo Build: ${BUILD_TYPE} -j${THREAD_COUNT} ${stat}
    echo GUI Deps: ${BUILD_GUI_DEPS}
    echo Extras: ${BUILD_EXTRAS}
    echo No AES: ${NO_AES}

}

