name: ci/gh-actions/docker

on:
    push:
        tags:
            - '*'

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v6
                with:
                    file: ./Dockerfile
                    push: true
                    tags: sn1f3rt/nerva:latest, sn1f3rt/nerva:${{ github.ref_name }}
